services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: docker-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'pruebas'
      MYSQL_USER: 'alumno'
      MYSQL_PASSWORD: 'alumno'
      MYSQL_ROOT_PASSWORD: 'administrador'
    ports:
      - '6606:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/conf.d


volumes:
    mysql-data:
