services:
  php:
    image: php:8.2-fpm
    build: ./php
    container_name: docker_php2
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=alumnopassword
      - MYSQL_DB=futbol
      - MONGODB_HOST=host.docker.internal
      - MONGODB_USER=alumno
      - MONGODB_PASSWORD=alumno
      - MONGODB_DB=employees
      - MONGODB_PORT=27017

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php