
//asegurarnos que el servidor esté en marcha
//ej:  node server_express.js

### para recibir todas las ciudades
get http://localhost:3000/ciudades 

### para recibir por código de ciudad
get http://localhost:3000/ciudades/VAL

### para modificar datos
post http://localhost:3000/ciudades/MAD
Content-Type: application/json

{
    "nombre": "Madrid Capital",
    "poblacion": 4500000
        }

###
put http://localhost:3000/ciudades/MAD
Content-Type: application/json

{
    "nombre": "Madrid Capital",
    "poblacion": 4500000
        }
###
get http://localhost:3000/ciudades/MAD

### Para añadir datos
POST http://localhost:3000/ciudades
Content-Type: application/json

{
  "codigo": "VLL",
  "nombre": "Valladolid",
  "poblacion": 300000
}
###
POST http://localhost:3000/ciudades
Content-Type: application/json

{
  "codigo": "MAD",
  "nombre": "Madrid",
  "poblacion": 500000
}

### Para borrar datos
DELETE  http://localhost:3000/ciudades/MAD


###
#######################################################
###
get http://localhost:3000/suma/8/4

###
get http://localhost:3000/resta/8/4


###
get http://localhost:3000/division/8/4

###
get http://localhost:3000/divisor/8/4

###
#######################################################
###
get http://localhost:3000/ciudadAerop
###
GET http://localhost:3000/ciudadAerop/MAD/aeropuertos
###
POST http://localhost:3000/ciudadAerop/ALI
Content-Type: application/json

{
  "codigo": "ALI",
  "nombre": "Alicante",
  "poblacion": 300000,
  "aeropuertos": [
            { "codigo": "ALT", "nombre": "El Altet" }
        ]
}
###
POST http://localhost:3000/ciudadAerop/ALI
Content-Type: application/json

{
  "codigo": "ALI",
  "nombre": "Alicante",
  "poblacion": 300000,
  "aeropuertos": [
            { "codigo": "ALT", "nombre": "El Altet" }
        ]
}

###
POST http://localhost:3000/ciudadAerop/ALI/aeropuertos
Content-Type: application/json

{
  "codigo": "NEW",
  "nombre": "Nuevo aeropuerto" 
}

###
DELETE  http://localhost:3000/ciudadAerop/ALI
