
//asegurarnos que el servidor esté en marcha
//ej:  node server_express.js

### para recibir todas las ciudades
get http://localhost:3000/ciudades 

### para recibir por código de ciudad
get http://localhost:3000/ciudades/VAL

### para modificar datos
post http://localhost:3000/ciudades/MAD
Content-Type: application/json

{
    "nombre": "Madrid Capital",
    "poblacion": 4500000
        }

###
put http://localhost:3000/ciudades/MAD
Content-Type: application/json

{
    "nombre": "Madrid Capital",
    "poblacion": 4500000
        }
###
get http://localhost:3000/ciudades/MAD

### Para añadir datos
PUT http://localhost:3000/ciudades
Content-Type: application/json

{
  "codigo": "BGT",
  "nombre": "Bogotá",
  "poblacion": 300000
}
###
POST http://localhost:3000/ciudades
Content-Type: application/json

{
  "codigo": "MAD",
  "nombre": "Madrid",
  "poblacion": 500000
}

### Para borrar datos
DELETE  http://localhost:3000/ciudades/MAD



###
#######################################################
###
get http://localhost:3000/suma/8/4

###
get http://localhost:3000/resta/8/4


###
get http://localhost:3000/division/8/4

###
get http://localhost:3000/divisor/8/4

###
#######################################################
###
get http://localhost:3000/ciudadAerop

### Obtener todos los aeropuertos de una ciudad
GET http://localhost:3000/ciudadAerop/MAD/aeropuertos


### Añadir una ciudad
POST http://localhost:3000/ciudadAerop/ALI
Content-Type: application/json

{
  "codigo": "ALI",
  "nombre": "Alicante",
  "poblacion": 300000,
  "aeropuertos": [
            { "codigo": "ALT", "nombre": "El Altet" }
        ]
}

### Añadir un aeropuerto a una ciudad
POST http://localhost:3000/ciudadAerop/ALI/aeropuertos
Content-Type: application/json

{
  "codigo": "NEW",
  "nombre": "Nuevo aeropuerto" 
}

### Eliminar un aeropuerto de una ciudad
DELETE  http://localhost:3000/ciudadAerop/ALI/aeropuertos/ALT

### Dado el código de un aeropuerto, obtener la ciudad a la que pertenece
GET http://localhost:3000/aeropuerto/TOJ
